[Info]

;Вариант. 0 - если у задачи нет вариантов. Числа 1, 2, ... если есть.
Variant=0

;Условие
Text="Дан код программы:</p><p><pre class=\"prettyprint linenums no-scroll\"><code>
#include &lt;iostream&gt;
#include &lt;cmath&gt;
struct DataException : std::exception
{
DataException(float d1, float d2, char *str)
: a(d1), b(d2), msg(str){ }
float a, b;
char *msg;
};
float MRoot(float x, float y)
{
double z = x * y;
if (z &gt; 1e+70)
throw DataException(x, y, \"Переполнение!\");
if (x &lt; 0 && y &gt; 0)
throw DataException(x, y, \"Отрицателен 1-й параметр\");
if (x &gt; 0 && y &lt; 0)
throw DataException(x, y, \"Отрицателен 2-й параметр\");
return (float)sqrt(z);
}

void DataExceptionTesting()
{
setlocale(LC_CTYPE, \"Russian\");
try
{
  std::cout &lt;&lt;\"MRoot(x,t) = \"&lt;&lt;MRoot(16., 9.) &lt;&lt; std::endl;  //1
  std::cout &lt;&lt;\"MRoot(x,t) = \"&lt;&lt;MRoot(1.6e38,9e36)&lt;&lt;std::endl;//2
  std::cout &lt;&lt;\"MRoot(x,t) = \"&lt;&lt;MRoot(16., -9.) &lt;&lt; std::endl; //3
}
catch (DataException e)
{
  std::cout &lt;&lt; e.msg&lt;&lt;\" x = \"&lt;&lt; e.a &lt;&lt;\" y = \"&lt;&lt; e.b &lt;&lt;std::endl;
}
} 
</code></pre></p><p>Какие строки будут присутствовать в результате выполнения функции DataExceptionTesting()</p><p>"

;Сложность в диапазоне [1-5]
Difficulty=4

;Тема
Topic="Перехват исключений"

;ID Темы
TopicId=581

;Автор
Author="Боловцов С.В."

;Имя решателя (не изменять)
Solver="Test"

[Solution]
Type = "multi"

Multi[] = "MRoot(x,t) = 12"
ResponseOptions[]="MRoot(x,t) = 12"
Multi[] = "Переполнение! x = 1.6e+038 y = 9e+036"
ResponseOptions[]="Переполнение! x = 1.6e+038 y = 9e+036"
ResponseOptions[]="Отрицат. 2-й парам. x = 16, y = -9"



[DataBase]
TaskId=1048
GroupTaskId=1000
